
services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "latest"
      MOTD: "Young ni"
      MODE: "survival"
      MAX_PLAYERS: "50"
      DIFFICULTY: "hard"
      OPS: |
        Panda047
      SERVER_NAME: "Ling Nota Rip YOur OFf"
      VIEW_DISTANCE: "8"
      SPAWN_PROTECTION: "1"
      SEED: "-3609821817241206192"
      OVERRIDE_ICON: true
      ICON: /icon.jpg
    volumes:
      - ./serverdata:/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
