
services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "latest"
      MOTD: "Young ni"
      MODE: "survival"
      MAX_PLAYERS: "50"
      DIFFICULTY: "hard"
      OPS: |
        Panda047
      SERVER_NAME: "Ling Nota Rip YOur OFf"
      VIEW_DISTANCE: "8"
      SPAWN_PROTECTION: "1"
      SEED: "-3609821817241206192"
      ICON: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.reddit.com%2Fr%2FPixelArt%2Fcomments%2F16sxjtu%2Ftotoro_64x64%2F&psig=AOvVaw3m3RDNGcEJEDaRRqJFVdnh&ust=1743733187246000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCIi5h7vmuowDFQAAAAAdAAAAABAE"
    volumes:
      - ./serverdata:/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
