
services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      TYPE: "PAPER"
      EULA: "TRUE"
      VERSION: "latest"
      MOTD: "Ling Nota Rip YOur OFf"
      MODE: "survival"
      MAX_PLAYERS: "30"
      DIFFICULTY: "hard"
      OPS: |
        Panda047
      SERVER_NAME: "Ling Nota Rip YOur OFf"
      VIEW_DISTANCE: "8"
      SIMULATION_DISTANCE: "3"
      SPAWN_PROTECTION: "1"
      # RESOURCE_PACK: "https://cdn.modrinth.com/data/jOgTDzFc/versions/zoRys6IH/Adventure%20Time.zip"
      # REQUIRE_RESOURCE_PACK: "true"
      # RESOURCE_PACK_PROMPT: "Please download this resource pack to play properly!"
      SEED: "-3609821817241206192"
    volumes:
      - ./serverdata:/data
      - ./server-icon.png:/data/server-icon.png
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
